name: Run Scripts Daily

on:
  schedule:
    # Run at 9:00 PM Philippines time (UTC+8), which is 1:00 PM UTC
    - cron: '0 13 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
      
      - name: Run index.js
        run: node index.js
        env:
          JENNINA_USERNAME: ${{ secrets.JENNINA_USERNAME }}
          JENNINA_PASSWORD: ${{ secrets.JENNINA_PASSWORD }}
          BREVO_USN: ${{ secrets.BREVO_USN }}
          BREVO_PASS: ${{ secrets.BREVO_PASS }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
      
      - name: Run sendMail.js
        run: node sendMail.js
        env:
          BREVO_USN: ${{ secrets.BREVO_USN }}
          BREVO_PASS: ${{ secrets.BREVO_PASS }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }} 