name: Run Scripts Daily

on:
  schedule:
    - cron: '30 12 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
      
      - name: Create output directory
        run: mkdir -p output
      
      - name: Create empty output files if they don't exist
        run: |
          touch output/lateEntries.txt
          touch output/noChecklist.txt
          touch output/reminders.txt
      
      - name: Run index.js
        run: node index.js
        env:
          NODE_ENV: production
          JENNINA_USERNAME: ${{ secrets.JENNINA_USERNAME }}
          JENNINA_PASSWORD: ${{ secrets.JENNINA_PASSWORD }}
          BREVO_USN: ${{ secrets.BREVO_USN }}
          BREVO_PASS: ${{ secrets.BREVO_PASS }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
      
      - name: Run sendMail.js
        run: node sendMail.js
        env:
          NODE_ENV: production
          BREVO_USN: ${{ secrets.BREVO_USN }}
          BREVO_PASS: ${{ secrets.BREVO_PASS }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }} 
